<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat Password_psw-repeat</name>
   <tag></tag>
   <elementGuidId>6cb9a1c9-3a1a-417d-83a1-ec17fe915448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;psw-repeat&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='psw-repeat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40817aa0-e56f-4b90-985a-295ccef1dd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>119c4d18-89c6-42d6-ac16-aa5498ccfd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repeat Password</value>
      <webElementGuid>a95ed7e4-f21e-44c0-81c4-f4698a579cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>psw-repeat</value>
      <webElementGuid>656fe963-79ac-4bb3-8918-86024221b31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML1&quot;)/div[@class=&quot;widget-content&quot;]/form[1]/div[@class=&quot;container&quot;]/input[3]</value>
      <webElementGuid>97f9fcac-6fe2-4eea-b40f-9d0d40b222c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='psw-repeat']</value>
      <webElementGuid>cafb4f12-86e0-45c9-a58d-cecc6b425c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML1']/div/form/div/input[3]</value>
      <webElementGuid>4e08064a-9915-4a2f-b00b-e2f19d5d91de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>ce829a48-331b-40c1-8b01-72d7c8154283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Repeat Password' and @name = 'psw-repeat']</value>
      <webElementGuid>d9fc6131-40d0-43bc-a710-0f197858e003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
