<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AcceptedW3CCapabilityKeys</name>
   <tag></tag>
   <elementGuidId>21d9f3ac-e572-4bcf-80a3-0084e139f7de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AcceptedW3CCapabilityKeys')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82c5d224-b769-41eb-adee-3cc5d0caa567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys.html</value>
      <webElementGuid>1a384629-00c7-4221-bb5b-55785522f4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium</value>
      <webElementGuid>17a42906-6d15-4680-badd-9d1b29185403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>fde1e3ec-1f09-421e-a8b5-4cdf5a799b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys</value>
      <webElementGuid>4056838b-f5e7-4ad1-ace1-c12257b96b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[2]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>c53e097a-4cc8-4546-a7a4-e05254e67b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>6ba28c0d-f932-4c8d-b0fe-a3b6643addec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>832a8acc-2824-43fd-a870-b4d62ae416f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/following::a[1]</value>
      <webElementGuid>df307a47-a58e-4799-b706-f3aee214fb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WrapsElement'])[1]/following::a[1]</value>
      <webElementGuid>52ce9f7c-9cd2-40bf-bc32-8ff804034611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BuildInfo'])[1]/preceding::a[1]</value>
      <webElementGuid>174b57a4-b69e-4805-8700-6b2aa93319e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By'])[1]/preceding::a[2]</value>
      <webElementGuid>477eca76-b22b-4f5b-84e5-25bc55fe13f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AcceptedW3CCapabilityKeys']/parent::*</value>
      <webElementGuid>44e55d0e-7713-4b61-b852-0255302c7051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AcceptedW3CCapabilityKeys.html')]</value>
      <webElementGuid>31d7ffa8-21b8-4ef9-a77a-0d46d9571b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li/a</value>
      <webElementGuid>4a50f396-f9eb-4b4c-9fba-62c3dd522623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'AcceptedW3CCapabilityKeys.html' and @title = 'class in org.openqa.selenium' and (text() = 'AcceptedW3CCapabilityKeys' or . = 'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>8a083219-9ad3-4d7d-9ede-e513197ae704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
